baseurl = "https://cloudnatives.uk"
title = "Cloud Natives UK"
theme = "pulp"
canonifyurls = false
hasCJKLanguage = false
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Cloud Natives UK"
    avatar = "cnuklogo.png"
    description = "Bringing together Cloud Native and Kubernetes communities across the UK"
    publicationYear = "2023"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "events"
    name = "Events"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/events/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/cloudnativesuk"
    weight = 20

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/cloudnativesuk"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:hello@cloudnatives.uk"
    weight = 40
